# Generated by Django 6.0.2 on 2026-06-13 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_bets', to='dashboard.match'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_bets', to='dashboard.participant'),
        ),
        migrations.CreateModel(
            name='TeamPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_picks', to='dashboard.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.team')),
            ],
        ),
    ]
