# Generated by Django 6.0.2 on 2026-06-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_bet_match_alter_bet_participant_teampick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='strength',
        ),
        migrations.AddField(
            model_name='team',
            name='american_odds',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='team',
            name='is_eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
